### ISSUE TITLE
Tabel met verplichting elementen is niet duidelijk voor Gekoppelde bron

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/Metadata-ISO19119#1]
De tabel https://docs.geostandaarden.nl/md/mdprofiel-iso19119/#appendix-verantwoording bevat per element de verplichting. Gekoppelde bron is conditioneel, maar de subelementen ervan staan op verplicht. Het lijkt mij logischer dat dit, net als bij de Thesaurus, dan ook conditionele elementen zijn. Of heb ik het verkeerd gelezen?

**Comment by idevisser** [comment]
nee een lastig dingetje, de subelementen zijn wel verplicht, zo kun je wel een "los" koppeltype hebben als er geen gekoppelde bron is en kun je de mogelijke operaties ook zonder dat deze op een vaste set data opereert worden opgegeven
