### ISSUE TITLE
Link [CSW ISO Metadata AP] in respec doc is incorrect

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/Metadata-ISO19119#2]
Link verwijst nu naar: 
```https://docs.geostandaarden.nl/md/mdprofiel-iso19119/portal.opengeospatial.org/files/?artifact_id=21460```

Moet zijn: ```https://portal.opengeospatial.org/files/?artifact_id=21460```

**Comment by idevisser** [comment]
Volgens mij staat dit in de config.js van de werkversie al goed.
