### ISSUE TITLE
in service metadata zijn bepaalde kwaliteitsrapporten niet relevant

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/Metadata-ISO19119#5]
denk aan nauwkeurigheid, compleetheid, topologische samenhang

**Comment by thijsbrentjens** [comment]
Logisch. Waar ben je dit tegen gekomen? Moet er ergens iets aangepast worden? Kan je iets meer informatie geven @pvgenuchten ?

**Comment by idevisser** [comment]
@pvgenuchten is dit nog relevant? moet ik iets in het profiel hiervoor aanpassen?

**Comment by idevisser** [comment]
@pvgenuchten ik sluit dit issue, als je meer info hebt, kunnen we het weer openenen
